{% set version = "1.6.6" %}

{% if dagster_epoch is defined and dagster_epoch == "eight" %}
  {% set dagster_python = "python >=3.8,<3.9" %}
  {% set dagster_pendulum = "pendulum >=0.7.0,<4" %}
  {% set dagster_protobuf = "protobuf >=3.20.0,<5" %}
  {% set dagster_universal_pathlib = "universal_pathlib >=0.2.0" %}
  {% set dagster_only_core = True %}
{% elif dagster_epoch is defined and dagster_epoch == "nine" %}
  {% set dagster_python = "python >=3.9,<3.10" %}
  {% set dagster_pendulum = "pendulum >=0.7.0,<4" %}
  {% set dagster_protobuf = "protobuf >=3.20.0,<5" %}
  {% set dagster_universal_pathlib = "universal_pathlib >=0.2.0" %}
  {% set dagster_only_core = True %}
{% elif dagster_epoch is defined and dagster_epoch == "ten" %}
  {% set dagster_python = "python >=3.10,<3.11" %}
  {% set dagster_pendulum = "pendulum >=0.7.0,<4" %}
  {% set dagster_protobuf = "protobuf >=3.20.0,<5" %}
  {% set dagster_universal_pathlib = "universal_pathlib >=0.2.0" %}
  {% set dagster_only_core = False %}
{% elif dagster_epoch is undefined or dagster_epoch == "eleven" %}
  {% set dagster_python = "python >=3.11,<3.12" %}
  {% set dagster_pendulum = "pendulum >=0.7.0,<4" %}
  {% set dagster_protobuf = "protobuf >=4,<5" %}
  {% set dagster_universal_pathlib = "universal_pathlib >=0.2.0" %}
  {% set dagster_only_core = True %}
{% elif dagster_epoch is defined and dagster_epoch == "twelve" %}
  {% set dagster_python = "python >=3.12" %}
  {% set dagster_pendulum = "pendulum =3,<4" %}
  {% set dagster_protobuf = "protobuf >=4,<5" %}
  {% set dagster_universal_pathlib = "universal_pathlib" %}
  {% set dagster_only_core = True %}
{% endif %}

package:
  name: dagster-meta
  version: {{ version }}

source:
  # uses main version
  - folder: dagster-pipes
    url: https://pypi.io/packages/source/d/dagster-pipes/dagster-pipes-{{ version }}.tar.gz
    sha256: 67467f11b10ce441ba8b3f0ce7e3ed203991c614f4a7fd0642befe625d50434e

  - folder: dagster
    url: https://pypi.io/packages/source/d/dagster/dagster-{{ version }}.tar.gz
    sha256: 295a6646eafc6360eea328194d224a27a39d4697da7c8495468ea215ee80c975

{% if not dagster_only_core %}
  - folder: dagster-webserver
    url: https://pypi.io/packages/source/d/dagster-webserver/dagster-webserver-{{ version }}.tar.gz
    sha256: b3ed08ac55a4700e8190b7f552b152e6d7e055b4d5d54f9f3eb123faeb8e5151

  - folder: dagit
    url: https://pypi.io/packages/source/d/dagit/dagit-{{ version }}.tar.gz
    sha256: 5b725d324334bec0d7f6738af2fac48f1d540074f09003ed623900cc2cadd37f

  - folder: dagster-graphql
    url: https://pypi.io/packages/source/d/dagster-graphql/dagster-graphql-{{ version }}.tar.gz
    sha256: abf1df81961c74443586b9ed1dd62c8aecb1e2df1b68f63238425cd786a200dd

  - folder: dagster-airflow
    url: https://pypi.io/packages/source/d/dagster-airflow/dagster-airflow-{{ version }}.tar.gz
    sha256: f58a5806951b1ead24c7a05da817bf466e84d340c33024faa29d8513e7c87de5
{% endif %}


build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8


test:
  commands:
    - echo "tests in outputs"


outputs:
  - name: dagster-pipes
    build:
      version: {{ version }}
      noarch: python
      script: cd dagster-pipes && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
    test:
      requires:
        - pip
      imports:
        - dagster_pipes
      commands:
        - pip check

    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-pipes/LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - name: dagster
    build:
      noarch: python
      version: {{ version }}
      entry_points:
        - dagster = dagster.cli:main
        - dagster-daemon = dagster.daemon.cli:main
      script: cd dagster && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage("dagster-pipes", max_pin="x.x.x") }}
        - {{ dagster_pendulum }}
        - {{ dagster_protobuf }}
        - {{ dagster_universal_pathlib }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - click >=5.0
        - coloredlogs >=6.1,<=14.0
        - croniter >=0.3.34
        - docstring_parser
        - grpcio >=1.44.0
        - grpcio-health-checking >=1.44.0
        - jinja2
        - packaging >=20.9
        - psutil >=1.0
        - pydantic >1.10.0,!=1.10.7,<3
        - python >=3.8
        - python-dateutil
        - python-dotenv
        - pytz
        - pywin32-on-windows
        - pyyaml >=5.1
        - rich
        - requests
        - setuptools
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - typing_extensions >=4.4.0,<5
        - watchdog >=0.8.3
      run_constrained:
        - pywin32 !=226
        - {{ dagster_python }}

    test:
      requires:
        - python >=3.8
        - pip
      imports:
        - dagster
        - dagster.api
        - dagster.check
        - dagster.cli
        - dagster.config
        - dagster.core.definitions
        - dagster.core.events
        - dagster.core.execution
        - dagster.core.executor
        - dagster.core.host_representation
        - dagster.core.instance
        - dagster.core.launcher
        - dagster.core.run_coordinator
        - dagster.core.scheduler
        - dagster.core.selector
        - dagster.core.snap
        - dagster.core.storage
        - dagster.core.system_config
        - dagster.core.types
        - dagster.core.workspace
        - dagster.daemon
        - dagster.grpc
        - dagster.loggers
        - dagster.seven
        - dagster.utils
      commands:
        - pip check
        - dagster --help
        - dagster-daemon --help

    about:
      home: https://github.com/dagster-io/dagster
      license: Apache-2.0
      license_family: APACHE
      summary: The data orchestration platform built for productivity.
      doc_url: https://dagster.readthedocs.io
      license_file: dagster/LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

{% if not dagster_only_core %}

  - name: dagster-webserver
    build:
      version: {{ version }}
      noarch: python
      script: cd dagster-webserver && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      entry_points:
        - dagster-webserver = dagster_webserver.cli:main
        - dagster-webserver-debug = dagster_webserver.debug:main

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - {{ pin_subpackage("dagster-graphql", max_pin="x.x.x") }}
        - click >=7.0,<9.0
        - starlette !=0.36.0
        - uvicorn-standard
    test:
      requires:
        - python >=3.8
        - pip
      imports:
        - dagster_webserver
      commands:
        - pip check
        - dagster-webserver --help
        - dagster-webserver-debug --help

    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-webserver/LICENSE
      summary: Web UI for dagster.

  - name: dagster-graphql
    build:
      version: {{ version }}
      noarch: python
      entry_points:
        - dagster-graphql = dagster_graphql.cli:main
      script: cd dagster-graphql && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - gql-with-requests >=3.0.0,<4.0.0
        - graphene >=3,<4
        - python >=3.8
        - requests
        - starlette

    test:
      requires:
        - python >=3.8
        - pip
      imports:
        - dagster_graphql
        - dagster_graphql.client
        - dagster_graphql.schema
      commands:
        - dagster-graphql --help
        - pip check

    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-graphql/LICENSE
      summary: The GraphQL frontend to python dagster.

  - name: dagster-airflow
    build:
      noarch: python
      version: {{ version }}
      script:
        # TODO: remove after https://github.com/dagster-io/dagster/pull/9932
        - {{ PYTHON }} -c '__import__("pathlib").Path("dagster-airflow/dagster_airflow/hooks/__init__.py").touch()'
        - {{ PYTHON }} -c '__import__("pathlib").Path("dagster-airflow/dagster_airflow/links/__init__.py").touch()'
        - cd dagster-airflow && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - docker-py >=5.0.3,<6
        - lazy-object-proxy
        - pendulum >=0.7.0,<3
        - python >=3.8
        - python-dateutil >=2.8.0

    test:
      requires:
        - python >=3.8
        - pip
        - apache-airflow-providers-docker
        - jinja2 <3
        # TODO: remove after https://github.com/conda-forge/airflow-feedstock/pull/92
        - pathspec >=0.9.0,<0.10.0
      imports:
        - dagster_airflow
      commands:
        - pip check

    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-airflow/LICENSE
      summary: Airflow plugin for Dagster

  - name: dagit
    build:
      noarch: python
      version: {{ version }}
      entry_points:
        - dagit = dagster_webserver.cli:main
        - dagit-debug = dagster_webserver.debug:main
      script: cd dagit && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - {{ pin_subpackage("dagster-webserver", max_pin="x.x.x") }}
        - python >=3.8

    test:
      requires:
        - python >=3.8
        - pip
      imports:
        - dagit
      commands:
        - pip check
        - dagit --help

    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_family: APACHE
      license_file: dagit/LICENSE
      summary: Dagster UI

{% endif %}

about:
  home: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_family: APACHE
  license_file: dagster/LICENSE
  doc_url: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
